# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.11

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - Static Analysis
  - Documentation

pylint:
  stage: Static Analysis
  script:
    - pip install pylint --quiet
    - pip3 install -r requirements.txt
    - find plotter/ -type f -name "*.py" | xargs pylint --exit-zero | tee pylint.txt
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - echo "Pylint score was $score"

pages:
  stage: Documentation
  script:
    - pip3 install -r requirements.txt
    - python -m pip install -e .
    - sphinx-apidoc -f -e -o docs/source plotter/
    - cd docs
    - sphinx-build -b html source public
    - cd ..
    - mv docs/public .
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
